[input]
cwd = "res/src/lvgl"
files = [ "lvgl.h" ]
auto_scan = true

[generation]
root_namespace = "lv"
classes = [
    "obj",
    { ident = "img", inherits = ["obj"] },
    { ident = "anim", inherits = ["obj"] }
]
namespaces = [
    "tick",
    "mem"
]
