[input]
cwd = "res/lvgl"
files = [ "lvgl.h" ]
auto_scan = true

[generation]
target = "c++20"
root_namespace = "lv"
classes = [
    "obj",
    { ident = "img", inherits = ["obj"] },
    { ident = "anim", inherits = ["obj"] }
]
namespaces = [
    "tick",
    "mem"
]
