[input]
cwd = "res/lvgl/"

[generation]
target = "c++20"
classes = [
    "obj",
    { ident = "img", inherits = ["obj"] },
    { ident = "anim", inherits = ["obj"] }
]
namespaces = [
    "tick",
    "mem",
    "event",
]
